name: flutter_model
description: "Model codec interfaces for flutter_msgs"
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_writer:
    path: ../flutter_writer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
